name: 'btc_economics_dataset'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'btc_economics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  btc_economics_dataset:  # Changed from 'btc_economics' to match project name
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts

# Use static values for development
vars:
  minio_endpoint: "localhost:9000"
  minio_access_key: "admin"
  minio_secret_key: "password"
  minio_bucket_coingecko: "coingecko-data"
  minio_bucket_fred: "fred-data"
  minio_bucket_blockstream: "bronze"